
# Ascent Variables
.ornl_environment_template:
  variables:
    SCHEDULER_PARAMETERS: "-P CSC359 -nnodes 1 -W 120"
    WORKDIR: /gpfs/wolf/proj-shared/csc359/ci/${CI_PIPELINE_ID}

.SVC-Account-Cleanup:
  stage: .pre
  tags:
    - batch 
  variables:
    SCHEDULER_PARAMETERS: "-P CSC359 -nnodes 1 -W 120"
  script:
    - export WORKDIR="/gpfs/wolf/proj-shared/csc359/ci/"
    # clears directory of files more than 1 hour/60 minutes old
    - find $WORKDIR -D -type d -mindepth 1 -mmin +60 -prune -print -exec rm -rf {} \; || true
    - ls -hal $WORKDIR    
  allow_failure: true
  resource_group: cleanup

.resolve_build_script:
  script:
    # Do _not_ clean up WORKDIR as files are needed for testing
    - |
      mkdir -p "$WORKDIR"
      cp -r . "$WORKDIR"
      cd "$WORKDIR"
      export srcdir=$WORKDIR builddir=$WORKDIR/build installdir=$WORKDIR/install
      mkdir build
      ls
      ./buildsystem/build.sh 
      chmod -R +X ./build
      source buildsystem/ascent-env.sh
      cd build
      ctest -vv
      make install
      make test_install

cleanup:
 stage: .pre
 extends: .SVC-Account-Cleanup

 # For Ascent CI
Ascent-Build-Test:
  stage: build
  tags:
    - batch
  extends:
    - .resolve_build_script
    - .ornl_environment_template

.report-status:
  variables:
    GIT_STRATEGY: none
    STATUS_PROJECT: ORNL/ReSolve
    MY_CLUSTER: Ascent
  tags:
    - nobatch
  extends:
    - .ornl_environment_template
  script:
    # For complete details on the GitLab API please see:
    # https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit
    # Make sure to create the token with Developer level access and API scope
    - |
      curl -L -X POST -H @${GITHUB_CURL_HEADERS} https://api.github.com/repos/${STATUS_PROJECT}/statuses/${CI_COMMIT_SHA} -d "{\"state\":\"${CI_JOB_NAME}\",\"target_url\":\"${CI_PIPELINE_URL}\",\"context\":\"${MY_CLUSTER}\"}"
  environment:
    name: reporting-gitlab

pending:
  extends:
    - .report-status
  stage: .pre

success:
  stage: .post
  extends:
    - .report-status
  
failure:
  stage: .post
  extends:
    - .report-status
  rules:
    - when: on_failure

