#!/bin/bash

foo="";

for i in 0{0..9};
do
foo=" ${foo} ${i} ${i}"
done

for i in {10..21};
do
foo=" ${foo} ${i} ${i}"
done


matfile="$HOME/testcases/ACTIVSg10k_AC/matrix_ACTIVSg10k_AC_"

rhsfile="$HOME/testcases/ACTIVSg10k_AC/rhs_ACTIVSg10k_AC_"


./$1 $matfile $rhsfile 10 $foo
