Deception Build:
  extends:
    - .cluster_build
    - .deception
  variables:
    SCRIPT_ARGS: " --build-only "

Deception Test:
  extends:
    - .cluster_test
    - .deception
  variables:
    CTESTARGS: " --timeout 240 --output-on-failure -LE deception-skip "
    SCRIPT_ARGS: " --test-only "
  needs: ['Deception Build']

pending:
  variables:
    MY_CLUSTER: "Deception"
  extends:
    - .report-pending
  stage: .pre

success:
  variables:
    MY_CLUSTER: "Deception"
  extends:
    - .report-status
  stage: .post
       
failure:
  stage: .post
  variables:
    MY_CLUSTER: "Deception"
  extends:
    - .report-status
  rules:
    - when: on_failure