name: documentation

on: workflow_dispatch 
# on: [pull_request]


permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12' 
      - name: Install pip dependencies
        run: pip3 install --no-cache-dir \
                  sphinx \
                  docutils \
                  sphinx_rtd_theme \
                  breathe \
                  m2r2
      - name: Install apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with: 
          packages: doxygen graphviz git graphviz ttf-freefont cmake
          version: 1.0.0
      - name: Doxygen Build
        run: |
          pushd docs
          sphinx-build . ./sphinx/_build
          doxygen ./doxygen/Doxyfile.in
          popd
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/sphinx/_build/
          force_orphan: true
